displayName=Pet The Animals
author=AhDoozy
description=Adds a 'Pet' option to friendly NPCs and displays fun messages.
tags=fun,cosmetic,interaction,roleplay,npcs,pet,animals,animal,animal responses,
plugins=com.pettheanimals.PetTheAnimalsPlugin